import Head from "next/head";
import React from "react";
import Header from "../Header";

type Props = {
  children?: React.ReactNode
}

export default function Layout({ children }:Props) {
  return (
    <>
      <Head>
        <title>POC Thiago Saytson Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {children}
    </>
  )
}